// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct DelayedSelfMessageClientProgram;
impl sails_rs::client::Program for DelayedSelfMessageClientProgram {}
pub trait DelayedSelfMessageClient {
    type Env: sails_rs::client::GearEnv;
    fn delayed_self_message(
        &self,
    ) -> sails_rs::client::Service<delayed_self_message::DelayedSelfMessageImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> DelayedSelfMessageClient
    for sails_rs::client::Actor<DelayedSelfMessageClientProgram, E>
{
    type Env = E;
    fn delayed_self_message(
        &self,
    ) -> sails_rs::client::Service<delayed_self_message::DelayedSelfMessageImpl, Self::Env> {
        self.service(stringify!(DelayedSelfMessage))
    }
}
pub trait DelayedSelfMessageClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
    ) -> sails_rs::client::PendingCtor<DelayedSelfMessageClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> DelayedSelfMessageClientCtors
    for sails_rs::client::Deployment<DelayedSelfMessageClientProgram, E>
{
    type Env = E;
    fn new(
        self,
    ) -> sails_rs::client::PendingCtor<DelayedSelfMessageClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod delayed_self_message {
    use super::*;
    pub trait DelayedSelfMessage {
        type Env: sails_rs::client::GearEnv;
        fn cancel(&mut self) -> sails_rs::client::PendingCall<io::Cancel, Self::Env>;
        fn expire(
            &mut self,
            user: ActorId,
            version: u64,
        ) -> sails_rs::client::PendingCall<io::Expire, Self::Env>;
        fn renew(
            &mut self,
            delay_blocks: u32,
        ) -> sails_rs::client::PendingCall<io::Renew, Self::Env>;
        fn start(
            &mut self,
            delay_blocks: u32,
        ) -> sails_rs::client::PendingCall<io::Start, Self::Env>;
        fn get_lock(&self, user: ActorId) -> sails_rs::client::PendingCall<io::GetLock, Self::Env>;
    }
    pub struct DelayedSelfMessageImpl;
    impl<E: sails_rs::client::GearEnv> DelayedSelfMessage
        for sails_rs::client::Service<DelayedSelfMessageImpl, E>
    {
        type Env = E;
        fn cancel(&mut self) -> sails_rs::client::PendingCall<io::Cancel, Self::Env> {
            self.pending_call(())
        }
        fn expire(
            &mut self,
            user: ActorId,
            version: u64,
        ) -> sails_rs::client::PendingCall<io::Expire, Self::Env> {
            self.pending_call((user, version))
        }
        fn renew(
            &mut self,
            delay_blocks: u32,
        ) -> sails_rs::client::PendingCall<io::Renew, Self::Env> {
            self.pending_call((delay_blocks,))
        }
        fn start(
            &mut self,
            delay_blocks: u32,
        ) -> sails_rs::client::PendingCall<io::Start, Self::Env> {
            self.pending_call((delay_blocks,))
        }
        fn get_lock(&self, user: ActorId) -> sails_rs::client::PendingCall<io::GetLock, Self::Env> {
            self.pending_call((user,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Cancel () -> ());
        sails_rs::io_struct_impl!(Expire (user: ActorId, version: u64) -> ());
        sails_rs::io_struct_impl!(Renew (delay_blocks: u32) -> ());
        sails_rs::io_struct_impl!(Start (delay_blocks: u32) -> ());
        sails_rs::io_struct_impl!(GetLock (user: ActorId) -> Option<super::Lock>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum DelayedSelfMessageEvents {
            Started {
                user: ActorId,
                version: u64,
                expires_at: u32,
            },
            Renewed {
                user: ActorId,
                version: u64,
                expires_at: u32,
            },
            Cancelled {
                user: ActorId,
                version: u64,
            },
            Expired {
                user: ActorId,
                version: u64,
            },
        }
        impl sails_rs::client::Event for DelayedSelfMessageEvents {
            const EVENT_NAMES: &'static [Route] = &["Started", "Renewed", "Cancelled", "Expired"];
        }
        impl sails_rs::client::ServiceWithEvents for DelayedSelfMessageImpl {
            type Event = DelayedSelfMessageEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Lock {
    pub active: bool,
    pub expires_at: u32,
    pub version: u64,
}
