// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct OracleAdminWrapperClientProgram;
impl sails_rs::client::Program for OracleAdminWrapperClientProgram {}
pub trait OracleAdminWrapperClient {
    type Env: sails_rs::client::GearEnv;
    fn admin_oracle(&self) -> sails_rs::client::Service<admin_oracle::AdminOracleImpl, Self::Env>;
    fn market(&self) -> sails_rs::client::Service<market::MarketImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> OracleAdminWrapperClient
    for sails_rs::client::Actor<OracleAdminWrapperClientProgram, E>
{
    type Env = E;
    fn admin_oracle(&self) -> sails_rs::client::Service<admin_oracle::AdminOracleImpl, Self::Env> {
        self.service(stringify!(AdminOracle))
    }
    fn market(&self) -> sails_rs::client::Service<market::MarketImpl, Self::Env> {
        self.service(stringify!(Market))
    }
}
pub trait OracleAdminWrapperClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
    ) -> sails_rs::client::PendingCtor<OracleAdminWrapperClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> OracleAdminWrapperClientCtors
    for sails_rs::client::Deployment<OracleAdminWrapperClientProgram, E>
{
    type Env = E;
    fn new(
        self,
    ) -> sails_rs::client::PendingCtor<OracleAdminWrapperClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod admin_oracle {
    use super::*;
    pub trait AdminOracle {
        type Env: sails_rs::client::GearEnv;
        /// Override the base `update_price` method and enforce admin access.
        fn update_price(
            &mut self,
            value: u128,
        ) -> sails_rs::client::PendingCall<io::UpdatePrice, Self::Env>;
        /// Reads the latest stored price.
        fn get_price(&self) -> sails_rs::client::PendingCall<io::GetPrice, Self::Env>;
    }
    pub struct AdminOracleImpl;
    impl<E: sails_rs::client::GearEnv> AdminOracle for sails_rs::client::Service<AdminOracleImpl, E> {
        type Env = E;
        fn update_price(
            &mut self,
            value: u128,
        ) -> sails_rs::client::PendingCall<io::UpdatePrice, Self::Env> {
            self.pending_call((value,))
        }
        fn get_price(&self) -> sails_rs::client::PendingCall<io::GetPrice, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(UpdatePrice (value: u128) -> ());
        sails_rs::io_struct_impl!(GetPrice () -> u128);
    }
}

pub mod market {
    use super::*;
    pub trait Market {
        type Env: sails_rs::client::GearEnv;
        /// A command that uses the admin_oracle price and applies a slippage guard.
        ///
        /// In real protocols, similar checks protect users from stale/attacked admin_oracle prices.
        fn open_position(
            &mut self,
            amount_tokens: u128,
            max_acceptable_price: u128,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env>;
        /// Query the last stored quote (shows that Market has its own state).
        fn last_quote(&self) -> sails_rs::client::PendingCall<io::LastQuote, Self::Env>;
        /// Pure quote based on the admin_oracle price.
        /// This is a typical “read path” that depends on admin_oracle but does not mutate admin_oracle state.
        fn quote_usd(
            &self,
            amount_tokens: u128,
        ) -> sails_rs::client::PendingCall<io::QuoteUsd, Self::Env>;
    }
    pub struct MarketImpl;
    impl<E: sails_rs::client::GearEnv> Market for sails_rs::client::Service<MarketImpl, E> {
        type Env = E;
        fn open_position(
            &mut self,
            amount_tokens: u128,
            max_acceptable_price: u128,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env> {
            self.pending_call((amount_tokens, max_acceptable_price))
        }
        fn last_quote(&self) -> sails_rs::client::PendingCall<io::LastQuote, Self::Env> {
            self.pending_call(())
        }
        fn quote_usd(
            &self,
            amount_tokens: u128,
        ) -> sails_rs::client::PendingCall<io::QuoteUsd, Self::Env> {
            self.pending_call((amount_tokens,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(OpenPosition (amount_tokens: u128, max_acceptable_price: u128) -> u128);
        sails_rs::io_struct_impl!(LastQuote () -> (u128,ActorId,));
        sails_rs::io_struct_impl!(QuoteUsd (amount_tokens: u128) -> u128);
    }
}
