import { GearApi, decodeAddress } from "@gear-js/api";
import { TypeRegistry } from "@polkadot/types";
import {
  TransactionBuilder,
  ActorId,
  getServiceNamePrefix,
  getFnNamePrefix,
  ZERO_ADDRESS,
} from "sails-js";

// ─── Event types ──────────────────────────────────────────────────────────────

type Minted   = { to: ActorId; value: bigint };
type Burned   = { from: ActorId; value: bigint };
type Approval = { owner: ActorId; spender: ActorId; value: bigint };
type Transfer = { from: ActorId; to: ActorId; value: bigint };

// SCALE codec type descriptors for event decoding
const types = {
  Minted:   { to: "[u8;32]", value: "U256" },
  Burned:   { from: "[u8;32]", value: "U256" },
  Approval: { owner: "[u8;32]", spender: "[u8;32]", value: "U256" },
  Transfer: { from: "[u8;32]", to: "[u8;32]", value: "U256" },
};

// ─── Program ─────────────────────────────────────────────────────────────────

/// Sails-JS client for a deployed VFT (Vara Fungible Token) program.
///
/// This class is typically generated by the Sails IDL toolchain. It is
/// included here as a self-contained example showing how to interact with
/// a VFT contract from a Node.js backend without a browser wallet.
export class Program {
  public readonly registry: TypeRegistry;
  public readonly vft: Service;

  constructor(public api: GearApi, private _programId?: `0x${string}`) {
    this.registry = new TypeRegistry();
    this.registry.setKnownTypes({ types });
    this.registry.register(types);
    this.vft = new Service(this);
  }

  public get programId(): `0x${string}` {
    if (!this._programId) throw new Error("Program ID is not set");
    return this._programId;
  }

  /// Upload a new VFT program from compiled WASM bytecode.
  newCtorFromCode(
    code: Uint8Array | Buffer,
    name: string,
    symbol: string,
    decimals: number
  ): TransactionBuilder<null> {
    const builder = new TransactionBuilder<null>(
      this.api,
      this.registry,
      "upload_program",
      ["New", name, symbol, decimals],
      "(String, String, String, u8)",
      "String",
      code
    );
    this._programId = builder.programId;
    return builder;
  }

  /// Instantiate a VFT program from an already-uploaded CodeId.
  newCtorFromCodeId(
    codeId: `0x${string}`,
    name: string,
    symbol: string,
    decimals: number
  ): TransactionBuilder<null> {
    const builder = new TransactionBuilder<null>(
      this.api,
      this.registry,
      "create_program",
      ["New", name, symbol, decimals],
      "(String, String, String, u8)",
      "String",
      codeId
    );
    this._programId = builder.programId;
    return builder;
  }
}

// ─── Service ─────────────────────────────────────────────────────────────────

/// Exposes all methods of the `Vft` service from the VFT program IDL.
///
/// Command methods (burn, mint, transfer, approve, ...) return a `TransactionBuilder`
/// that must be signed and sent by the caller.
///
/// Query methods (balanceOf, totalSupply, name, symbol, decimals, ...) use
/// `api.message.calculateReply()` for a read-only simulation — no gas cost,
/// no on-chain state change.
export class Service {
  constructor(private _program: Program) {}

  private decodeEvent<E>(sig: string, payload: Uint8Array): E {
    const result = this._program.registry.createType(sig, payload) as any;
    return result[2].toJSON() as E;
  }

  // ── Commands ──────────────────────────────────────────────────────────────

  public burn(
    from: ActorId,
    value: number | string | bigint
  ): TransactionBuilder<boolean> {
    if (!this._program.programId) throw new Error("Program ID is not set");
    return new TransactionBuilder<boolean>(
      this._program.api,
      this._program.registry,
      "send_message",
      ["Vft", "Burn", from, value],
      "(String, String, [u8;32], U256)",
      "bool",
      this._program.programId
    );
  }

  public mint(
    to: ActorId,
    value: number | string | bigint
  ): TransactionBuilder<boolean> {
    if (!this._program.programId) throw new Error("Program ID is not set");
    return new TransactionBuilder<boolean>(
      this._program.api,
      this._program.registry,
      "send_message",
      ["Vft", "Mint", to, value],
      "(String, String, [u8;32], U256)",
      "bool",
      this._program.programId
    );
  }

  public transfer(
    to: ActorId,
    value: number | string | bigint
  ): TransactionBuilder<boolean> {
    if (!this._program.programId) throw new Error("Program ID is not set");
    return new TransactionBuilder<boolean>(
      this._program.api,
      this._program.registry,
      "send_message",
      ["Vft", "Transfer", to, value],
      "(String, String, [u8;32], U256)",
      "bool",
      this._program.programId
    );
  }

  public approve(
    spender: ActorId,
    value: number | string | bigint
  ): TransactionBuilder<boolean> {
    if (!this._program.programId) throw new Error("Program ID is not set");
    return new TransactionBuilder<boolean>(
      this._program.api,
      this._program.registry,
      "send_message",
      ["Vft", "Approve", spender, value],
      "(String, String, [u8;32], U256)",
      "bool",
      this._program.programId
    );
  }

  // ── Queries ───────────────────────────────────────────────────────────────

  /// Read the token balance of `account`.
  /// This is the primary method used by the token gate for access control.
  public async balanceOf(
    account: ActorId,
    originAddress?: string,
    value?: number | string | bigint,
    atBlock?: `0x${string}`
  ): Promise<bigint> {
    const payload = this._program.registry
      .createType("(String, String, [u8;32])", ["Vft", "BalanceOf", account])
      .toHex();

    const reply = await this._program.api.message.calculateReply({
      destination: this._program.programId,
      origin: originAddress ? decodeAddress(originAddress) : ZERO_ADDRESS,
      payload,
      value: value || 0,
      gasLimit: this._program.api.blockGasLimit.toBigInt(),
      at: atBlock,
    });

    if (!reply.code.isSuccess) {
      throw new Error(
        this._program.registry
          .createType("String", reply.payload)
          .toString()
      );
    }

    const result = this._program.registry.createType(
      "(String, String, U256)",
      reply.payload
    );
    return (result[2] as any).toBigInt();
  }

  public async totalSupply(
    originAddress?: string,
    value?: number | string | bigint,
    atBlock?: `0x${string}`
  ): Promise<bigint> {
    const payload = this._program.registry
      .createType("(String, String)", ["Vft", "TotalSupply"])
      .toHex();

    const reply = await this._program.api.message.calculateReply({
      destination: this._program.programId,
      origin: originAddress ? decodeAddress(originAddress) : ZERO_ADDRESS,
      payload,
      value: value || 0,
      gasLimit: this._program.api.blockGasLimit.toBigInt(),
      at: atBlock,
    });

    if (!reply.code.isSuccess) {
      throw new Error(
        this._program.registry.createType("String", reply.payload).toString()
      );
    }

    const result = this._program.registry.createType(
      "(String, String, U256)",
      reply.payload
    );
    return (result[2] as any).toBigInt();
  }

  public async name(originAddress?: string): Promise<string> {
    const payload = this._program.registry
      .createType("(String, String)", ["Vft", "Name"])
      .toHex();

    const reply = await this._program.api.message.calculateReply({
      destination: this._program.programId,
      origin: originAddress ? decodeAddress(originAddress) : ZERO_ADDRESS,
      payload,
      value: 0,
      gasLimit: this._program.api.blockGasLimit.toBigInt(),
    });

    if (!reply.code.isSuccess) {
      throw new Error(
        this._program.registry.createType("String", reply.payload).toString()
      );
    }

    const result = this._program.registry.createType(
      "(String, String, String)",
      reply.payload
    );
    return (result[2] as any).toString();
  }

  // ── Events ────────────────────────────────────────────────────────────────

  public subscribeToTransferEvent(
    callback: (data: Transfer) => void | Promise<void>
  ): Promise<() => void> {
    return this._program.api.gearEvents.subscribeToGearEvent(
      "UserMessageSent",
      ({ data: { message } }) => {
        if (
          !message.source.eq(this._program.programId) ||
          !message.destination.eq(ZERO_ADDRESS)
        )
          return;

        const payload = message.payload.toHex();
        if (
          getServiceNamePrefix(payload) === "Vft" &&
          getFnNamePrefix(payload) === "Transfer"
        ) {
          void Promise.resolve(
            callback(
              this.decodeEvent<Transfer>(
                "(String, String, Transfer)",
                message.payload
              )
            )
          ).catch(console.error);
        }
      }
    );
  }

  public subscribeToMintedEvent(
    callback: (data: Minted) => void | Promise<void>
  ): Promise<() => void> {
    return this._program.api.gearEvents.subscribeToGearEvent(
      "UserMessageSent",
      ({ data: { message } }) => {
        if (
          !message.source.eq(this._program.programId) ||
          !message.destination.eq(ZERO_ADDRESS)
        )
          return;

        const payload = message.payload.toHex();
        if (
          getServiceNamePrefix(payload) === "Vft" &&
          getFnNamePrefix(payload) === "Minted"
        ) {
          void Promise.resolve(
            callback(
              this.decodeEvent<Minted>(
                "(String, String, Minted)",
                message.payload
              )
            )
          ).catch(console.error);
        }
      }
    );
  }
}
