// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct FactoryClientProgram;
impl sails_rs::client::Program for FactoryClientProgram {}
pub trait FactoryClient {
    type Env: sails_rs::client::GearEnv;
    fn factory(&self) -> sails_rs::client::Service<factory::FactoryImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> FactoryClient
    for sails_rs::client::Actor<FactoryClientProgram, E>
{
    type Env = E;
    fn factory(&self) -> sails_rs::client::Service<factory::FactoryImpl, Self::Env> {
        self.service(stringify!(Factory))
    }
}
pub trait FactoryClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        code_id: CodeId,
    ) -> sails_rs::client::PendingCtor<FactoryClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> FactoryClientCtors
    for sails_rs::client::Deployment<FactoryClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        code_id: CodeId,
    ) -> sails_rs::client::PendingCtor<FactoryClientProgram, io::New, Self::Env> {
        self.pending_ctor((code_id,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (code_id: CodeId) -> ());
}

pub mod factory {
    use super::*;
    pub trait Factory {
        type Env: sails_rs::client::GearEnv;
        fn create_program(&mut self)
        -> sails_rs::client::PendingCall<io::CreateProgram, Self::Env>;
    }
    pub struct FactoryImpl;
    impl<E: sails_rs::client::GearEnv> Factory for sails_rs::client::Service<FactoryImpl, E> {
        type Env = E;
        fn create_program(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::CreateProgram, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(CreateProgram () -> ActorId);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum FactoryEvents {
            /// Emitted when a new child program instance is successfully created.
            /// Contains the newly created program's ActorId (address).
            ProgramCreated(ActorId),
        }
        impl sails_rs::client::Event for FactoryEvents {
            const EVENT_NAMES: &'static [Route] = &["ProgramCreated"];
        }
        impl sails_rs::client::ServiceWithEvents for FactoryImpl {
            type Event = FactoryEvents;
        }
    }
}
